# const.py

DOMAIN = "ansible_playbook"
DEFAULT_NAME = "Ansible Playbook"
DEFAULT_ICON = "mdi:book-play"
DEFAULT_LIMIT = "all"
DEFAULT_TAGS = "all"
DEFAULT_OPTIONS = None

CONF_NAME = "name"
CONF_PLAYBOOK_DIRECTORY = "directory"
CONF_PLAYBOOK_FILE = "playbook_file"
CONF_HOSTS = "hosts"
CONF_SWITCH_NAME = "switch_name"
CONF_SWITCH_ID = "switch_id"
CONF_LIMIT = "limit"
CONF_TAGS = "tags"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_SUDO = "sudo"
CONF_SUDO_USER = "sudo_user"
CONF_EXTRA_VARS = "extra_vars"
CONF_OPTIONS = "options"
CONF_PLAYBOOKS = "playbooks"
CONF_VAULT_PASSWORD_FILE = "fault_password_file"

ATTR_OK_COUNT = "ok_count"
ATTR_FAILURE_COUNT = "failure_count"
ATTR_CHANGED_COUNT = "changed_count"
ATTR_SKIPPED_COUNT = "skipped_count"
ATTR_IGNORED_COUNT = "ignored_count"
ATTR_PLAYBOOK = "playbook"
ATTR_TAGS = "tags"
ATTR_LIMIT = "limit"
ATTR_OPTIONS = "options"

SERVICE_PLAY = "play"
SERVICE_STOP = "stop"
